version: "3.9"

services:
  ms-membership:
    image: kabraass/ecommerce-membership:1.0
    container_name: ms-membership
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network

  ms-product:
    image: kabraass/ecommerce-product:1.0
    container_name: ms-product
    ports:
      - "8082:8082"
    networks:
      - ecommerce-network

  ms-order:
    image: kabraass/ecommerce-order:1.0
    container_name: ms-order
    ports:
      - "8083:8083"
    environment:
      - USER_SERVICE_URL=http://ms-membership:8081
      - PRODUCT_SERVICE_URL=http://ms-product:8082
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
