global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'membership'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-membership:8081']

  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-product:8082']

  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-order:8083']